"""Add task_assessments table

Revision ID: ac8ac4441e4f
Revises: 5d6eb4560229
Create Date: 2025-09-03 15:35:56.237588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8ac4441e4f'
down_revision = '5d6eb4560229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_assessments',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('assessment_content', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False, min_value=0.0, max_value=100.0),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('assessor_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assessments_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_assessments_employee_id'))

    op.drop_table('task_assessments')
    # ### end Alembic commands ###
